# Generated by Django 4.0.4 on 2022-05-23 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='SFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fats', models.FloatField(verbose_name='Жиры')),
                ('carbohydrates', models.FloatField(verbose_name='Углеводы')),
                ('squirrels', models.FloatField(verbose_name='Белки')),
            ],
            options={
                'verbose_name': 'БЖУ',
                'verbose_name_plural': 'БЖУ',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255, verbose_name='Имя пользоватлея')),
                ('mail', models.CharField(max_length=255, verbose_name='Почта')),
                ('reviews', models.IntegerField(verbose_name='Количество одобрений')),
                ('dishes', models.IntegerField(verbose_name='Рецептов')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('creator', models.CharField(max_length=255, verbose_name='Автор')),
                ('ingredients', models.TextField(verbose_name='Ингредиенты')),
                ('text', models.TextField(verbose_name='Текст рецепта')),
                ('calories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapi.sfc', verbose_name='Калории')),
                ('category', models.ManyToManyField(to='mainapi.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
        migrations.CreateModel(
            name='HistoricalSFC',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('fats', models.FloatField(verbose_name='Жиры')),
                ('carbohydrates', models.FloatField(verbose_name='Углеводы')),
                ('squirrels', models.FloatField(verbose_name='Белки')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical БЖУ',
                'verbose_name_plural': 'historical БЖУ',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
