# Generated by Django 4.0.4 on 2022-05-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapi', '0002_historicalusers_historicalrecipe_historicalcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsfc',
            old_name='squirrels',
            new_name='proteins',
        ),
        migrations.RenameField(
            model_name='sfc',
            old_name='squirrels',
            new_name='proteins',
        ),
        migrations.AlterField(
            model_name='historicalusers',
            name='nickname',
            field=models.CharField(max_length=255, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='nickname',
            field=models.CharField(max_length=255, verbose_name='Имя пользователя'),
        ),
    ]
